---
- name: Include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Change listen_adresses
  lineinfile: 
    dest: "{{ postgresql_conf_path }}"
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '{{ listen_addresses_config }}'"
    state: present
  notify: Restart postgresql

- name: Change listen_adresses
  lineinfile: 
    dest: "{{ pg_hba_conf_path }}"
    line: "host    all             all             {{ item }}             md5" 
    state: present
  loop: "{{ listen_addresses }}"
  notify: Restart postgresql

- name: Flush handlers
  meta: flush_handlers

- name: Ensure postgresql is running and enabled
  service:
    name: postgresql
    state: started
    enabled: true

- name: Change postgres user password
  become: true
  become_user: postgres
  postgresql_user:
    name: postgres
    password: "{{ postgres_password }}"

- name: Create databases
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ item.database }}"
  loop: "{{ databases }}"

- name: Create users
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
  loop: "{{ databases }}"

- name: Grant permissions
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ item.database }}"
    role: "{{ item.user }}"
    privs: ALL
    type: database
  loop: "{{ databases }}"

- name: Create firewall rule
  firewalld:
    service: postgresql
    zone: public
    state: enabled
    permanent: yes
    immediate: yes