---
dependencies: []

galaxy_info:
  author: Adrian Zech
  description: Install Zabbix Server
  company: Homelab

  license: license (MIT)

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - monitoring
    - zabbix
    - zabbix-server