---
- name: Add apt key
  apt_key:
    url: "{{ apt_key_url }}"
    state: present

- name: Add grafana repo
  apt_repository:
    repo: "{{ repo_url }}"
    state: present

- name: Update cache
  apt:
    update_cache: yes