---
- hosts: all
  remote_user: adrian
  become: true
  roles:
    - update
    - common
    - setup-ssh
    - mounts
    - zabbix-agent

- hosts: database
  remote_user: adrian
  become: true
  roles:
    - postgresql

- hosts: monitoring
  remote_user: adrian
  become: true
  roles:
    - zabbix-server
    
- hosts: podman
  remote_user: adrian
  become: true
  roles:
    - podman
    - containers

- hosts: media_server
  remote_user: adrian
  become: true
  roles:
    - plex