---
- hosts: all:!proxmox
  remote_user: adrian
  become: true
  roles:
    - update
    - common
    - motd
    - setup_ssh
    - mounts
    - zabbix_agent

- hosts: database
  remote_user: adrian
  become: true
  roles:
    - postgresql

- hosts: monitoring
  remote_user: adrian
  become: true
  roles:
    - zabbix_server

- hosts: podman
  remote_user: adrian
  become: true
  roles:
    - podman
    - containers

- hosts: media_server
  remote_user: adrian
  become: true
  roles:
    - plex
