---
- name: Include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include os specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install zabbix-agent
  package:
    name: "{{ package_name }}"
    state: latest

- name: Ensure zabbix-agent is running and enabled
  service:
    name: "{{ service_name }}"
    state: started
    enabled: true

- name: Install zabbix-agent config from template
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    mode: 0744
  notify: Restart zabbix-agent

- name: Create firewall rule
  firewalld:
    service: zabbix-agent
    zone: public
    state: enabled
    permanent: yes
    immediate: yes