---
- name: Upgrade all packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Check if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot server if required
  reboot:
    msg: "Reboot initiated by Ansible"
  when: reboot_required.stat.exists