---
container_name: nginx-proxy-manager-db

image: jc21/mariadb-aria
tag: latest

container_directories:
  - /opt/nginx-proxy-manager/data/mysql

container_ports:
  - 3306:3306

container_env:
  MYSQL_ROOT_PASSWORD: npm
  MYSQL_DATABASE: npm
  MYSQL_USER: npm
  MYSQL_PASSWORD: "{{ nginx_proxy_manager_database_password }}"

container_volumes:
  - /opt/nginx-proxy-manager/data/mysql:/var/lib/mysql

container_command: