---
container_name: nginx-proxy-manager

image: jc21/nginx-proxy-manager
tag: latest

container_directories:
  - /opt/nginx-proxy-manager/data
  - /opt/nginx-proxy-manager/letsencrypt

container_ports:
  - 8080:80
  - 8443:44
  - 8081:81

container_env:
  DB_MYSQL_HOST: 10.0.10.100
  DB_MYSQL_PORT: 3306
  DB_MYSQL_USER: npm
  DB_MYSQL_PASSWORD: "{{ nginx_proxy_manager_database_password }}"
  DB_MYSQL_NAME: npm
  DISABLE_IPV6: true

container_volumes:
  - /opt/nginx-proxy-manager/data:/data
  - /opt/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

container_command:
