---
container_name: unifi-controller

image: linuxserver/unifi-controller
tag: latest

container_directories:
  - /opt/unifi-controller

container_ports:
  - 3478:3478/udp
  - 10001:10001/udp
  - 8080:8080
  - 8443:8443
  - 1900:1900/udp
  - 8843:8843
  - 8880:8880
  - 6789:6789
  - 5514:5514/udp

container_env:
  PUID: 1000
  PGID: 1000

container_volumes:
  - /opt/unifi-controller:/config

container_command: