---
- name: Add docker.io to registries
  lineinfile:
    path: /etc/containers/registries.conf
    line: "[registries.search]"
    state: present

- name: Add docker.io to registries
  lineinfile:
    path: /etc/containers/registries.conf
    insertafter: '^[registries.search]'
    line: "registries = ['docker.io']"
    state: present