---
- name: Create containers accoring to hostname
  include_tasks: create_container.yml
  vars:
    - current_container: "{{ current_container_item }}"
  loop: "{{ lookup('vars', ansible_hostname) }}"
  loop_control:
    loop_var: current_container_item
