vm_name: gameserver-1
vm_id: 2100
vm_memory: 4096
vm_sockets: 2
vm_cores: 3
vm_disk_size: 40
vm_vlan_tag: 20
vm_bridge: vmbr0
vm_nameserver: 10.0.20.1
vm_gateway: 10.0.20.1
vm_ip_address: 10.0.20.100
vm_subnetmask: 24
vm_searchdomains: zech.lab
