vm_name: media-server
vm_id: 1200
vm_memory: 8192
vm_sockets: 2
vm_cores: 4
vm_disk_size: 20
vm_vlan_tag: 10
vm_bridge: vmbr0
vm_nameserver: 10.0.10.1
vm_gateway: 10.0.10.1
vm_ip_address: 10.0.10.200
vm_subnetmask: 24
vm_searchdomains: zech.lab
