---
user: adrian
myuid: 1000

owner: adrian
group: adrian

identity_provider:
  - authentik-redis
  - authentik-server
  - authentik-worker
  - nginx-proxy-manager-db
  - nginx-proxy-manager
database:
  - pgadmin
debian-testing-2:
  - uptime-kuma
home:
  - home-assistant
  - unifi-controller
cloud:
  - nextcloud-redis
  - nextcloud
  - nextcloud-onlyoffice
debian-testing-1:
  - wiki
  - dashboard
  - freshrss
media_stack:
  - sonarr
  - radarr
  - prowlarr
  - bazarr
  - sabnzbd
  - qbittorrent
  - tautulli
