---
- name: Include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Include os specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Configure vim
  lineinfile:
    path: "{{ vimrc_path }}"
    line: set tabstop=4

- name: Ensure cockpit is running and enabled
  service:
    name: cockpit.socket
    state: started
    enabled: true

- name: Remove dhcpv6-client firewall rule
  firewalld:
    service: dhcpv6-client
    permanent: true
    immediate: true
    state: disabled
