---
dependencies: []

galaxy_info:
  author: Adrian Zech
  description: Create Podman Containers
  company: Homelab

  license: license (MIT)

  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - bullseye

  galaxy_tags:
    - podman
    - container