---
- name: Include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include os specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Create systemd override directory
  file:
    path: "{{ systemd_override_path }}"
    state: directory
    recurse: true
    mode: 0755

- name: Install plex systemd override.conf
  template:
    src: override.conf.j2
    dest: "{{ systemd_override_path }}/override.conf"
    mode: 0644

- name: Install plex
  package:
    name: "{{ package_name }}"
    state: latest

- name: Stop plex
  service:
    name: "{{ service_name }}"
    state: stopped

- name: Change plex directory owner and group
  file:
    path: "{{ plex_path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    state: directory
    recurse: true

- name: Ensure plex is running and enabled
  service:
    name: "{{ service_name }}"
    daemon_reload: true
    state: started
    enabled: true

- name: Create firewall rule
  firewalld:
    service: plex
    zone: public
    state: enabled
    permanent: true
    immediate: true
